---
title: "Script"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 3
    #code_folding: hide
editor_options: 
  chunk_output_type: inline
---

<style type="text/css">
.title {
  display: none;
}

#getting-started img {
  margin-right: 10px;
}

</style>

<div class="row" style="padding-top: 20px;">

# Script  
## Week 1
### 1.1 ChIP-seq recap/discussion    
**Discuss**:  

- What is ChIP-seq? Presentation with ChIP-seq steps?    
- Sequencing samples. What happens in sequencer? What is the output?  
<br>

### 1.2 From data outputted by the sequencer to science   
[Seq2science](https://vanheeringen-lab.github.io/seq2science/index.html)  
*fastq file, bam processing, bigwig, peak calling, count table*  

**Discuss**:  

- Modify Siebrens pptx.  
- Fastq files, what does the data look like?  
- 4 lines of code with:  
    1. unique_read_name (starts with @-sign)  
    2. nucleotide sequence  
    3. `+` (previously, this line showed the same as line 1)  
    4. nucleotide quality score (Phred encoded)  
    
- The neccessary processing steps:  
  a. Read quality and adapter trimming   
  b. Aligning fastq reads to reference genome    
  c. BAM sieving.  
    - What considerations are important? PCR duplicates, multi mapping reaads    
    - Discuss use of input sample    
  d. Peak calling. Use of control samples. Narrow and Broad peaks?       
  e. Count table: What does it look?  
<br> 

### 1.3 Look at the read density yourself in a genome browser   
*Functional elements, ChIP signals, peaks, hypotheses about enrichment.*  

**Discuss**:  

- UCSC Genome Browser  
  * how to switch off tracks. Hide all tracks except for **GENCODE v32** and **Base Position**.     
  * how to browse trough the data  
  * how to upload custom data. Upload the <span style="color: red;">processed chip-seq data of histone marks in **heatlhy cells**, input and a **failed track** as .bigwig file. Or use trackhub?</span>  
    +  bigwig is a special data format to display dense, continuous data as graphs. The main advantage of this format is that only the portions of the files needed to dispaly a particular regoin are transferred making it considerably faster in a genome browsing tool [ref](https://genome.ucsc.edu/goldenPath/help/bigWig.html).    
  * As functional genomic elements: <span style="color: red;">upload custom track or use **ENCODE cCREs** track?</span>  

Now browse through the data.  

Peaks are ... 

**Assignments/Questions**:   

1. One of the tracks represents the input, which one and why?  
2. What kind of data is visualized in track "A"?  
3. Browse to these four regions, which one of them would you consider to display a peak (tip, make screenshot and paste in a temporary pptx. to compare the images)  
4. Of the marks visualized which ones are associated with gene expression and which ones with repression (from lecture)?  

**Discuss**:   
Peak calling software is used to identify peaks within a certain range of confidence. <span style="color: red;">and using replictes?</span>  

**Assignments/Questions**:

5. Which of the following influences the number of peaks identified:  
  - P-value threshold, the lower the fewer peaks  
  - read depth   
  - Q-value/false-discovery rate, the   
  - the type of control sample  ...   
  - 

**Discuss**:  

Upload peaks called by the software.  

**Assignments/Questions**:  

6. What are different functional genomic elements you have heard of during lectures?   

The custom track contains five tracks, numbered 1-5, representing different genomic elements.   

7. Which # represent what kind of element?   
8. Browse through the browser, estimate for each histone mark whether it is enriched in one or several of the genomic elements (1-5)   


## Week 2  
Look into: http://compgenomr.github.io/book/operations-on-genomic-intervals-with-genomicranges-package.html   

### 2.1 Introduction to Bioconductor  
**Bioconductor Packages:**   

- [Bioconductor](https://www.bioconductor.org/) provides tools for analysis of high throughput genomic data in R 
- Has its own repository, own way to install packages, each release designed with specific version of R  
- Install using BiocManager, the special installer for Bioconductor packages. The advantage over the 'standard' `install.pakages` command is that Bioconductor has different release cycles than regular R and BiocManager therefore recognizes the newest version better. Using `install.packages` you risk installing older versions (with more unfixed bugs and fewer features). In addition, BiocManager allows users to install packages from the 'devel' branch (under development), thus cutting-edge while `install.packages` points to the 'release' branch. Lastly, Bioconducter packages are heavily dependend on each other. It is therefor very important that they are from the same relase. Biocmanager checks that packages are from the same release.     

**Some important Bioconductor packages**  

Package | Purpose   
-----|-----   
[BSgenome](http://bioconductor.org/packages/release/bioc/html/BSgenome.html) | infrastructure and functions for related genome packages with full genome sequences for many species    
[Biostrings](https://www.bioconductor.org/packages/release/bioc/html/Biostrings.html) | provides containters and functions for fast manipulation of large biological sequences (aka genome data)   
[GenomicRanges](https://bioconductor.org/packages/release/bioc/vignettes/GenomicRanges/inst/doc/GenomicRangesIntroduction.html) | handles genomic intervals  
[GenomicFeatures](https://www.bioconductor.org/packages/release/bioc/html/GenomicFeatures.html) | functions to retrieve and manage genomic features from public databases  
[GenomicAlignments](https://bioconductor.org/packages/release/bioc/html/GenomicAlignments.html) | containers to store short sequence alignments for read counting, computing the coverage, junction detection, and working with the nucleotide content of the alignments     

```{r standard packages for cleaning and wrangling data }
library(tidyverse) # compilation of packages for usein data science. These packages are developed such that they nicely work together for data import, tidying, manipulation, visualization and programming  
library(GenomicRanges) # functions and data structures (containters) to handle genomic intervals which are datasets with notation chr-start-end. 
library(GenomicFeatures) # for functions to retrieve and manage genomic features (eg genes, exons, transcripts, promoters) from public databases  
library(GenomicAlignments) # containers to store short sequence alignments  
```

### 2.2 GenomicRanges   
**Discuss**:  

- how to import them and how to make them from scratch  
- convert dataframe to GRanges object with `as()`  
  + dataframe should have `start` `end` and `chr`  
  + `gr <- as(dataframe, "GRanges")`  
- minimally requires chr, start and end column from dataframe in input  
- also has metadata, `seqnames` and `seqinfo`  
- see ist of available accessors use: `methods(class = "GRanges")`  
  + `seqnames(gr)` - chromosome names  
  + `ranges(gr)` - returns IRanges object  
  + `mcols(gr)` - display metadata per range  
  + `seqinfo(gr)` - to store sequence information  
  + `genome(gr)`- genome name   
  + both are **setter** and **getter** functions  
  + can be inherited by other S4 objects  

### 2.3 GRangesList  
- container of collection of GRanges  
- construct with:  
  + `as(mylist, "GRangesList")`  
  + `GRangesList(myGranges1, myGranges2, ...)`
- convert back with `unlist()`  
- accessers found by `methods(class = "GRangesList")`  
- handy for eg. transcripts bij gene, exons by genes, read alignments, sliding windows 
  + `slidingWindows()` - makes sliding windows  
- `exonsBy()` function returns a GRangesList
<br>
Overlaps  
- `countOverlaps(query, subject)`  
- `findOverlaps(query, subject)`  
- `subsetByOverlap(query, subject)`  
- `overlapsAny()`  
- query and subject can be GRanges and GRangesList  

### 2.4 GenomicFeatures  
- manipulate TxDb objects from UCSC or BioMart  
- Transcript Database Objects
- Obtain TxDb object by: 
  + use `loadDB` as in `loadDB(system.file("extdata", "hg19_knownGene_sample.sqlite", package="GenomicFeatures"))`  
  + load TxDB annotation package like: `library(TxDb.Hsapiens.UCSC.hg19.knownGene)`  
<br>
Functions to manipulate TxDb object:  
- `genes()` function extracts genomic features from TxDb-like object.  
  + returns `GRanges` object  
- other functions to extract features are `transcripts()`, `cds()`, `exons()`, and `promoters()`  
  + input is TxDb object
  + define `filter = ` to filter a condition on a column as list    
  + define `columns = ` to select column names as list  

### 2.5 Custom data   
- reading BAM files  
- reading peak files and regions .BED files  

###   


## Week 3    
### Introduction  
We will be looking at data from BLUEPRINT, a consortium of European universities and research institutes aimed to systematically study/uncover the epigenomic landscape of cells found in the blood. 

'Normal' epigenome of a given cell. Producding reference epigenomes.  

Physiology and pathology (health and disease, development, lineage specification, onset and progression of disease, ) are both epigenetically regulated. 

We will look at the chromatin-based regulation of gene expression, thus the relationship between histone signatures (combination of histone marks) and gene expression

Epigenomic information, such as covalent histone modifications, DNA accessibility and DNA methylation  

**BLUEPRINT**  
- reference genemes of cells found in the blood  
- healthy individuals and with blood-based diseases including autoimmune diseases, leukemias.  

#### Use of thses insights:  
- epi-drugs  
- case stratification, improved diagnosis and progrnosis  

### Dataset  
1. lymphocytic leukemia?  
  
  - On the one hand, pathological tissues and cells exhibit epigenetic imprints of the developmental or differentiation stages from which they originate and, on the other hand, they acquire disease-specific epigenetic alterations  

2. innate immune cells/innate immune memory?  
  
  - comparing healthy with cancerous cells  
  - environmental stimuli can determine a cell's future response/behavior by altering its epigenetic state, and thus alter susceptibility to disease  


### Work
- looking at peaks  
- assessing enrichment  
- computing coverage  


